services:
  algodomo2mqtt:
    build: .
    container_name: algodomo2mqtt
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - ALGODOMO_CONFIG=/config/config.json
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/config
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
